version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle_db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - ./oracle/init.sql:/container-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build: ./backend
    container_name: bicicletas_backend
    ports:
      - "3000:3000"
    depends_on:
      - oracle
    environment:
      DB_USER: ${ORACLE_USER}
      DB_PASSWORD: ${ORACLE_PASSWORD}
      DB_HOST: oracle
      DB_PORT: 1521
      DB_NAME: ${ORACLE_DB}
    restart: always

  frontend:
    build: ./frontend
    container_name: bicicletas_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
