
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100),
    ESTADO VARCHAR2(20),
    CONTRASENA VARCHAR2(100),
    ADMINISTRADOR NUMBER(1,0) DEFAULT 0
);

CREATE TABLE TERMINAL (
    ID_TERMINAL NUMBER PRIMARY KEY,
    UBICACION VARCHAR2(100),
    CAPACIDAD NUMBER,
    BICICLETAS_DISPONIBLES NUMBER
);

CREATE TABLE RESERVA (
    ID_RESERVA NUMBER PRIMARY KEY,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO VARCHAR2(20),
    CODIGO_DESBLOQUEO VARCHAR2(50),
    ID_USUARIO NUMBER,
    ID_BICICLETA NUMBER,
    QR_PATH VARCHAR2(200)
);

CREATE TABLE REPORTE (
    ID_REPORTE NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    FECHA_REPORTE DATE,
    ESTADO VARCHAR2(20),
    ID_BICICLETA NUMBER,
    ID_USUARIO NUMBER
);

CREATE TABLE MANTENIMIENTO (
    ID_MANTENIMIENTO NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    FECHA_MANT DATE,
    TIPO VARCHAR2(50),
    ID_BICICLETA NUMBER
);

CREATE TABLE HISTORIAL (
    ID_HISTORIAL NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    ID_BICICLETA NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DESCRIPCION VARCHAR2(200),
    REPORTE VARCHAR2(200)
);

CREATE TABLE BICICLETA (
    ID_BICICLETA NUMBER PRIMARY KEY,
    ESTADO VARCHAR2(20),
    UBICACION VARCHAR2(100),
    MODELO VARCHAR2(50),
    FECHA_MANTE DATE,
    ID_TERMINAL NUMBER
);


CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_terminal START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_reserva START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_reporte START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_mantenimiento START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_historial START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_bicicleta START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE OR REPLACE PROCEDURE actualizar_estado_bicicleta(
    p_id_bicicleta IN NUMBER,
    p_nuevo_estado IN VARCHAR2
) AS
BEGIN
    UPDATE Bicicleta
    SET estado = p_nuevo_estado
    WHERE id_bicicleta = p_id_bicicleta;

    COMMIT;
END;
/
